# _target_: ito.model.ddpm.TLDDPM
# _partial_: true
# score_model_kwargs:
#   _target_: ito.model.cpainn.PaiNNTLScore
#   n_features: 64
#   max_lag: 1000
#   diff_steps: 1000
# lr: 0.001

_target_: models.ddpm.TLDDPM
lr: ${experiments.lr}
diffusion_steps: 1000

score_model_class: models.cpainn_mod.PaiNNTLScore
score_model_kwargs:
#     _target_: models.cpainn.PaiNNTLScore   # adjust import path to your class
    n_features: 64
    n_layers: 2
    max_lag: 1000
    diff_steps: ${..diffusion_steps}
    n_neighbors: 100
    n_types: 167
    dist_encoding: 'positional_encoding'
# ... any other kwargs PaiNNTLScore expects

