score_model_class: models.cpainn.PaiNNTLScore
score_model_kwargs:
  n_features: 64
  n_layers: 2
  max_lag: 1000
  diff_steps: 1000
  n_neighbors: 100
  n_types: 167
  dist_encoding: positional_encoding
diffusion_steps: 1000
lr: 0.001
