defaults:
  - _self_
  - model: ito
  - experiments: train
  - experiments@sample: sample
  - experiments@analysis: analysis
  - paths: default
  - data: data
  - data@dataloader: dataloader

project:
  name: E3TensorInterpolants