# configs/base.yaml
defaults:
  - model: E3FlowModel
  - data: thurlemann2023
  - experiment@exp_train: train
  - experiment@exp_eval:  eval
  - experiment@exp_analysis: analysis
  - paths: default
  - _self_

project:
  name: E3TensorInterpolants

seed: 69420
num_device: 1