_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 9
                - 50
                - 55
                - 77
                - 103
            "2":
                - 1
                - 9
                - 50
                - 55
                - 77
                - 103
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
epochs:
    value: 50
learning_rate:
    value: 0.001
